### ISSUE TITLE
您好,請問MoHW-Hosp-Data如何利用到er.mohw上

### ISSUE THREAD

**Issue by wotmshuaisi** [FlyMed/MoHW-Hosp-Data#2]
https://github.com/g0v/er.mohw

**Comment by Clementtang** [comment]
er.mohw 主要是針對急診病床去爬各醫院網站的公開資料並即時更新。而 mohw-hosp-data 的資料來源則為衛福部醫事機構評鑑資料，資料數量以及涵蓋的範圍會較廣 (但較不即時)，建議你可以參考本 repo 的資料來源及檔案說明。
